AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for read-only IAM policy and assumable role

Resources:
  ResourcesViewOnlyAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:Describe*
              - s3:Get*
              - s3:List*
              - iam:Get*
              - iam:List*
              - cloudwatch:Get*
              - cloudwatch:List*
              - cloudformation:Describe*
              - cloudformation:Get*
              - cloudformation:List*
              - logs:Describe*
              - logs:Get*
              - logs:List*
            Resource: '*'

  ViewOnlyAssumableRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ViewOnlyAssumableRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref ResourcesViewOnlyAccessPolicy

Outputs:
  RoleArn:
    Value: !GetAtt ViewOnlyAssumableRole.Arn